var pwdwidget = new PasswordWidget('thepwddiv', 'password');
        pwdwidget.MakePWDWidget();
        var frmvalidator = new Validator("register");
        frmvalidator.EnableOnPageErrorDisplay();
        frmvalidator.EnableMsgsTogether();
        frmvalidator.addValidation("name", "req", "Укажите корректное имя");
        frmvalidator.addValidation("email", "req", "Укажите корректный адрес email");
        frmvalidator.addValidation("email", "email", "Укажите корректный адрес email");
        frmvalidator.addValidation("username", "req", "Укажите корректный Логин");
        frmvalidator.addValidation("password", "req", "Укажите корректный пароль");